module.exports.song = [
  "When the night has come",
  "And the land is dark",
  "And the moon is the only light we'll see",
  "Oh I won't be afraid, no, I won't be afraid",
  "Just as long as you stand, stand by me",
  "So, Pumbaa, Pumbaa, stand by me",
  "Oh oh oh stand by me",
  "Ooh stand, stand by me, stand by me",
  "If the sky that we look upon",
  "Should tumble and fall",
  "Or the mountains, they should crumble to the sea",
  "I won't cry",
  "You won't cry?",
  "No, I won't shed a tear",
  "You won't shed a tear?",
  "Just as long as you stand, stand by me",
  "So, Pumbaa, Pumbaa, stand by me",
  "Oh oh won't you stand by me",
  "Ooh stand, stand by me, stand by me",
  "Eeh, I don't think I like this song!",
  "So, Pumbaa, Pumbaa, stand by me",
  "Oh oh won't you stand by me",
  "Ooh stand, come on, stand by me, stand by me",,
  "Timon?",
  "Yes?",
  "Can I sing the next song?",
  "Sure, as long as you stand by me!",
  "Fair enough.",
  "Whenever you're in trouble won't you stand by me",
  "Oh oh ooh stand by me",
  "I know you need me, stand by me",
  "Oh oh oh oh stand by me",
  "Oooh, heey"
];
